# Generated by Django 5.2.1 on 2025-05-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0002_payment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
