# Generated by Django 5.2.1 on 2025-05-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HARD", "Hardcover"), ("SOFT", "Softcover")],
                default="SOFT",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.PositiveIntegerField(),
        ),
    ]
